Repository instrumentisto/medea-flutter-webrtc, pull requests merged in 2021-11, with the labels that each got.

#3 Remove deprecated and unused APIs
  android/src/main/java/com/cloudwebrtc/webrtc/DataChannelObserver.java
  android/src/main/java/com/cloudwebrtc/webrtc/FlutterRTCVideoRenderer.java
  android/src/main/java/com/cloudwebrtc/webrtc/GetUserMediaImpl.java
  android/src/main/java/com/cloudwebrtc/webrtc/MethodCallHandlerImpl.java
  android/src/main/java/com/cloudwebrtc/webrtc/OrientationAwareScreenCapturer.java
  android/src/main/java/com/cloudwebrtc/webrtc/PeerConnectionObserver.java
  android/src/main/java/com/cloudwebrtc/webrtc/record/AudioChannel.java
  android/src/main/java/com/cloudwebrtc/webrtc/record/AudioSamplesInterceptor.java
  android/src/main/java/com/cloudwebrtc/webrtc/record/AudioTrackInterceptor.java
  android/src/main/java/com/cloudwebrtc/webrtc/record/FrameCapturer.java
  android/src/main/java/com/cloudwebrtc/webrtc/record/MediaRecorderImpl.java
  android/src/main/java/com/cloudwebrtc/webrtc/record/OutputAudioSamplesInterceptor.java
  android/src/main/java/com/cloudwebrtc/webrtc/record/VideoFileRenderer.java
  android/src/main/java/org/webrtc/audio/WebRtcAudioTrackUtils.java
  example/lib/main.dart
  example/lib/src/data_channel_sample.dart
  example/lib/src/get_user_media_sample.dart
  example/lib/src/get_user_media_sample_web.dart
  example/lib/src/loopback_sample.dart
  lib/flutter_webrtc.dart
  lib/src/interface/factory.dart
  lib/src/interface/media_recorder.dart
  lib/src/interface/navigator.dart
  lib/src/interface/rtc_data_channel.dart
  lib/src/interface/rtc_dtmf_sender.dart
  lib/src/interface/rtc_peerconnection.dart
  lib/src/interface/rtc_rtp_sender.dart
  lib/src/media_recorder.dart
  lib/src/native/factory_impl.dart
  lib/src/native/media_recorder_impl.dart
  lib/src/native/media_stream_track_impl.dart
  lib/src/native/mediadevices_impl.dart
  lib/src/native/navigator_impl.dart
  lib/src/native/rtc_data_channel_impl.dart
  lib/src/native/rtc_dtmf_sender_impl.dart
  lib/src/native/rtc_peerconnection_factory.dart
  lib/src/native/rtc_peerconnection_impl.dart
  lib/src/native/rtc_rtp_sender_impl.dart
  lib/src/web/factory_impl.dart
  lib/src/web/media_recorder_impl.dart
  lib/src/web/navigator_impl.dart
  lib/src/web/rtc_data_channel_impl.dart
  lib/src/web/rtc_dtmf_sender_impl.dart
  lib/src/web/rtc_peerconnection_factory.dart
  lib/src/web/rtc_peerconnection_impl.dart
  lib/src/web/rtc_rtp_sender_impl.dart
  lib/src/web/rtc_video_view_impl.dart
  test/unit/web/rtc_videw_view_test.dart
Labels: enhancement, k::refactor, k::api

#9 Disable context menu over RTCVideoView (#8)
  lib/src/native/mediadevices_impl.dart
  lib/src/native/rtc_rtp_sender_impl.dart
  lib/src/native/rtc_video_view_impl.dart
  lib/src/web/rtc_video_renderer_impl.dart
  lib/src/web/rtc_video_view_impl.dart
Labels: enhancement, k::api

#5 Bootstrap flutter_webrtc + rust + libwebrtc toolchain (#4)
  .editorconfig
  .env
  .github/workflows/ci.yml
  .gitignore
  .rustfmt.toml
  Cargo.lock
  Cargo.toml
  Makefile
  crates/libwebrtc-sys/Cargo.toml
  crates/libwebrtc-sys/build.rs
  crates/libwebrtc-sys/include/bridge.h
  crates/libwebrtc-sys/lib/.gitignore
  crates/libwebrtc-sys/src/bridge.cc
  crates/libwebrtc-sys/src/bridge.rs
  crates/libwebrtc-sys/src/lib.rs
  crates/native/Cargo.toml
  crates/native/build.rs
  crates/native/src/lib.rs
  example/lib/main.dart
  example/lib/src/test_sample.dart
  example/windows/.gitignore
  example/windows/CMakeLists.txt
  example/windows/flutter/CMakeLists.txt
  example/windows/flutter/generated_plugin_registrant.cc
  example/windows/flutter/generated_plugin_registrant.h
  example/windows/flutter/generated_plugins.cmake
  example/windows/runner/CMakeLists.txt
  example/windows/runner/Runner.rc
  example/windows/runner/flutter_window.cpp
  example/windows/runner/flutter_window.h
  example/windows/runner/main.cpp
  example/windows/runner/resource.h
  example/windows/runner/resources/app_icon.ico
  example/windows/runner/runner.exe.manifest
  example/windows/runner/utils.cpp
  example/windows/runner/utils.h
  example/windows/runner/win32_window.cpp
  example/windows/runner/win32_window.h
  windows/CMakeLists.txt
  windows/flutter_webrtc_plugin.cc
  windows/include/flutter_webrtc.h
  windows/include/flutter_webrtc/flutter_web_r_t_c_plugin.h
  windows/include/flutter_webrtc/flutter_webrtc_plugin.h
  windows/rust/include/flutter_webrtc_native.hpp
  windows/rust/lib/flutter_webrtc_native.dll
  windows/rust/lib/flutter_webrtc_native.dll.lib
  windows/src/flutter_webrtc.cc
Labels: enhancement, k::toolchain
