Repository instrumentisto/medea-flutter-webrtc, pull requests merged in 2021-12, with the labels that each got.

#15 Fix mirroring issues with `RTCVideoRenderer` (#14)
  lib/src/interface/rtc_video_renderer.dart
  lib/src/native/rtc_video_renderer_impl.dart
  lib/src/rtc_video_renderer.dart
  lib/src/web/rtc_video_view_impl.dart
Labels: enhancement, k::api, k::design

#18 Use cxx for Flutter `flutter-webrtc-native` interop
  .github/workflows/ci.yml
  Cargo.lock
  Makefile
  crates/libwebrtc-sys/Cargo.toml
  crates/libwebrtc-sys/build.rs
  crates/native/Cargo.toml
  crates/native/build.rs
  crates/native/src/lib.rs
  windows/.gitignore
  windows/CMakeLists.txt
  windows/rust/include/flutter_webrtc_native.hpp
  windows/rust/lib/flutter_webrtc_native.dll
  windows/rust/lib/flutter_webrtc_native.dll.lib
  windows/src/flutter_webrtc.cc
Labels: enhancement, k::refactor, k::api, k::toolchain, k::design

#11 Implement getSources method
  .clippy.toml
  Cargo.lock
  crates/libwebrtc-sys/Cargo.toml
  crates/libwebrtc-sys/build.rs
  crates/libwebrtc-sys/include/bridge.h
  crates/libwebrtc-sys/src/bridge.cc
  crates/libwebrtc-sys/src/bridge.rs
  crates/libwebrtc-sys/src/lib.rs
  crates/native/build.rs
  crates/native/src/lib.rs
  example/lib/main.dart
  example/lib/src/get_sources_sample.dart
  example/lib/src/test_sample.dart
  windows/src/flutter_webrtc.cc
Labels: k::documentation, enhancement, k::toolchain, k::design, platform::windows
