Repository instrumentisto/medea-flutter-webrtc, pull requests merged in 2023-07, with the labels that each got.

#117 Implement playout module using OpenAL
  .clippy.toml
  CHANGELOG.md
  Cargo.lock
  README.md
  crates/libwebrtc-sys/NOTICE
  crates/libwebrtc-sys/build.rs
  crates/libwebrtc-sys/include/adm.h
  crates/libwebrtc-sys/include/bridge.h
  crates/libwebrtc-sys/src/cpp/adm.cc
  crates/libwebrtc-sys/src/cpp/bridge.cc
  example/ios/Podfile.lock
  example/lib/src/loopback.dart
  example/macos/Podfile.lock
  example/pubspec.lock
  ios/medea_flutter_webrtc.podspec
  linux/CMakeLists.txt
  macos/medea_flutter_webrtc.podspec
  pubspec.yaml
  windows/CMakeLists.txt
Labels: enhancement, k::refactor, k::toolchain, platform::macos, platform::linux, feature

#119 Universalize default output device switching logic on desktop platforms
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  crates/libwebrtc-sys/.gitignore
  crates/libwebrtc-sys/build.rs
  crates/libwebrtc-sys/include/adm.h
  crates/libwebrtc-sys/src/cpp/adm.cc
  crates/native/Cargo.toml
  crates/native/src/devices.rs
  example/lib/src/get_sources.dart
  example/lib/src/on_device_change.dart
Labels: enhancement, k::refactor, k::api, k::design, platform::windows, platform::macos, platform::linux

#120 Fire `onDeviceChange` when changing linux default device
  CHANGELOG.md
  crates/native/src/devices.rs
Labels: enhancement, k::api, platform::linux

#121 Optmize webrtc context concurrent access
  crates/native/src/api.rs
  crates/native/src/bridge_generated.io.rs
  crates/native/src/bridge_generated.rs
  crates/native/src/devices.rs
  crates/native/src/lib.rs
  crates/native/src/pc.rs
  crates/native/src/user_media.rs
  lib/src/api/bridge.g.dart
  lib/src/api/bridge.g.freezed.dart
  lib/src/api/peer.dart
  lib/src/api/sender.dart
  lib/src/api/transceiver.dart
Labels: enhancement, k::refactor, platform::windows, platform::macos, platform::linux
