Repository instrumentisto/medea-flutter-webrtc, pull requests merged in 2023-05, with the labels that each got.

#109 Get track `facingMode` setting
  .github/workflows/ci.yml
  Cargo.lock
  Makefile
  android/src/main/kotlin/com/instrumentisto/medea_flutter_webrtc/MediaDevices.kt
  android/src/main/kotlin/com/instrumentisto/medea_flutter_webrtc/controller/MediaStreamTrackController.kt
  android/src/main/kotlin/com/instrumentisto/medea_flutter_webrtc/proxy/AudioMediaTrackSource.kt
  android/src/main/kotlin/com/instrumentisto/medea_flutter_webrtc/proxy/MediaStreamTrackProxy.kt
  android/src/main/kotlin/com/instrumentisto/medea_flutter_webrtc/proxy/VideoMediaTrackSource.kt
  crates/libwebrtc-sys/build.rs
  crates/libwebrtc-sys/src/bridge.rs
  crates/native/Cargo.toml
  crates/native/src/bridge_generated.io.rs
  crates/native/src/bridge_generated.rs
  crates/native/src/lib.rs
  crates/native/src/renderer.rs
  example/pubspec.lock
  example/pubspec.yaml
  ios/Classes/MediaDevices.swift
  ios/Classes/controller/MediaStreamTrackController.swift
  ios/Classes/proxy/MediaStreamTrackProxy.swift
  ios/Classes/proxy/VideoMediaTrackSourceProxy.swift
  lib/medea_flutter_webrtc.dart
  lib/src/api/bridge.g.dart
  lib/src/api/bridge.g.freezed.dart
  lib/src/model/constraints.dart
  lib/src/model/stats.dart
  lib/src/platform/native/media_stream_track.dart
  lib/src/platform/track.dart
  lib/src/platform/web/media_stream_track.dart
  pubspec.yaml
  windows/src/video_renderer.cc
Labels: enhancement, k::api, platform::windows, plarform::android, platform::ios, platform::macos, platform::linux, platform::web

#106 Prepare v0.8.0 release
  .github/workflows/ci.yml
  CHANGELOG.md
  CONTRIBUTING.md
  Cargo.lock
  LICENSE
  LICENSE.md
  NOTICE
  README.md
  android/build.gradle
  crates/native/Cargo.toml
  crates/native/src/bridge_generated.rs
  crates/native/src/devices.rs
  example/README.md
  example/ios/Podfile.lock
  example/macos/Podfile.lock
  example/pubspec.lock
  example/pubspec.yaml
  ios/medea_flutter_webrtc.podspec
  lib/src/api/bridge.g.dart
  lib/src/api/bridge.g.freezed.dart
  macos/medea_flutter_webrtc.podspec
  pubspec.yaml
Labels: k::documentation, enhancement, k::refactor, k::toolchain

#116 Prepare 0.8.1 release
  CHANGELOG.md
  example/ios/Podfile.lock
  example/macos/Podfile.lock
  example/pubspec.lock
  ios/medea_flutter_webrtc.podspec
  lib/src/api/peer.dart
  macos/medea_flutter_webrtc.podspec
  pubspec.yaml
Labels: k::documentation, enhancement, k::refactor
