Repository instrumentisto/medea-flutter-webrtc, pull requests merged in 2023-10, with the labels that each got.

#125 Implements extended API for creating `RtcRtpTransceivers`
  CHANGELOG.md
  Makefile
  android/gradle/wrapper/gradle-wrapper.properties
  android/src/main/kotlin/com/instrumentisto/medea_flutter_webrtc/model/Encoding.kt
  android/src/main/kotlin/com/instrumentisto/medea_flutter_webrtc/model/RtpTransceiverInit.kt
  crates/libwebrtc-sys/include/bridge.h
  crates/libwebrtc-sys/include/peer_connection.h
  crates/libwebrtc-sys/include/rtp_encoding_parameters.h
  crates/libwebrtc-sys/src/bridge.rs
  crates/libwebrtc-sys/src/cpp/bridge.cc
  crates/libwebrtc-sys/src/cpp/peer_connection.cc
  crates/libwebrtc-sys/src/cpp/rtp_encoding_parameters.cc
  crates/libwebrtc-sys/src/lib.rs
  crates/native/src/api.rs
  crates/native/src/bridge_generated.io.rs
  crates/native/src/bridge_generated.rs
  crates/native/src/lib.rs
  crates/native/src/pc.rs
  example/integration_test/webrtc_test.dart
  ios/Classes/controller/PeerConnectionController.swift
  ios/Classes/model/Encoding.swift
  ios/Classes/model/PeerConnectionConfiguration.swift
  lib/src/api/bridge.g.dart
  lib/src/api/bridge.g.freezed.dart
  lib/src/api/peer.dart
  lib/src/model/transceiver.dart
Labels: k::api, feature

#127 Update interaction with bridge
  lib/src/model/stats.dart
Labels: enhancement, k::refactor

#128 Fix dart event warning
  Cargo.lock
  crates/native/src/api.rs
  crates/native/src/bridge_generated.rs
  crates/native/src/renderer.rs
  example/ios/Podfile.lock
  example/ios/Runner.xcodeproj/project.pbxproj
  example/macos/Podfile.lock
  example/pubspec.lock
  lib/src/api/bridge.g.dart
  lib/src/api/bridge.g.freezed.dart
  lib/src/api/peer.dart
  lib/src/platform/native/video_renderer.dart
  linux/medea_flutter_webrtc_plugin.cc
  macos/Classes/VideoRenderer.h
  macos/Classes/VideoRenderer.m
  windows/include/video_renderer.h
  windows/src/video_renderer.cc
Labels: enhancement, k::refactor, k::api, platform::windows, platform::macos, platform::linux

#126 Fix OpenAL build
  crates/libwebrtc-sys/build.rs
Labels: enhancement, k::toolchain, platform::windows, k::dependencies

#130 Enable H264 codec
  crates/libwebrtc-sys/build.rs
  example/integration_test/webrtc_test.dart
Labels: enhancement, k::toolchain, platform::windows, platform::macos, platform::linux, k::testing

#133 Fix memory leak when using screensharing on macos
  CHANGELOG.md
  Cargo.lock
  crates/libwebrtc-sys/include/mouse_cursor_monitor_mac.h
  crates/libwebrtc-sys/include/screen_video_capturer.h
  crates/libwebrtc-sys/src/cpp/mouse_cursor_monitor_mac.mm
  crates/libwebrtc-sys/src/cpp/screen_video_capturer.cc
  example/pubspec.lock
Labels: enhancement, platform::macos, k::ui/ux, k::performance
