Repository instrumentisto/medea-flutter-webrtc, pull requests merged in 2024-09, with the labels that each got.

#170 Upgrade libwebrtc 128.0.6613.119
  CHANGELOG.md
  Cargo.lock
  README.md
  android/build.gradle
  crates/libwebrtc-sys/Cargo.toml
  crates/libwebrtc-sys/build.rs
  example/ios/Podfile.lock
  example/macos/Podfile.lock
  example/pubspec.lock
  ios/medea_flutter_webrtc.podspec
  macos/medea_flutter_webrtc.podspec
  pubspec.yaml
Labels: enhancement, k::dependencies

#171 Prepare 0.11.1 release
  CHANGELOG.md
  android/build.gradle
  example/ios/Podfile.lock
  example/macos/Podfile.lock
  example/pubspec.lock
  ios/medea_flutter_webrtc.podspec
  macos/medea_flutter_webrtc.podspec
  pubspec.yaml
Labels: k::documentation, enhancement

#172 Upgrade flutter_rust_bridge to v2.4.0
  CHANGELOG.md
  Cargo.lock
  android/build.gradle
  crates/native/Cargo.toml
  crates/native/src/frb_generated.rs
  example/ios/Podfile.lock
  example/lib/src/loopback.dart
  example/macos/Podfile.lock
  example/pubspec.lock
  ios/medea_flutter_webrtc.podspec
  lib/src/api/bridge/api.dart
  lib/src/api/bridge/frb_generated.dart
  lib/src/api/bridge/frb_generated.io.dart
  lib/src/api/bridge/lib.dart
  lib/src/api/bridge/renderer.dart
  macos/medea_flutter_webrtc.podspec
  pubspec.yaml
Labels: enhancement, k::toolchain, k::dependencies

#173 Implement `RtpReceiver.getCapabilities`
  CHANGELOG.md
  Cargo.lock
  android/src/main/kotlin/com/instrumentisto/medea_flutter_webrtc/controller/PeerConnectionFactoryController.kt
  crates/libwebrtc-sys/include/bridge.h
  crates/libwebrtc-sys/src/bridge.rs
  crates/libwebrtc-sys/src/cpp/bridge.cc
  crates/libwebrtc-sys/src/lib.rs
  crates/native/src/api/mod.rs
  crates/native/src/frb_generated.rs
  example/integration_test/webrtc_test.dart
  example/lib/src/video_codec_info.dart
  example/pubspec.lock
  ios/Classes/controller/PeerConnectionFactoryController.swift
  lib/medea_flutter_webrtc.dart
  lib/src/api/bridge/api.dart
  lib/src/api/bridge/frb_generated.dart
  lib/src/api/receiver.dart
  lib/src/api/sender.dart
Labels: k::api, platform::windows, plarform::android, platform::ios, platform::macos, platform::linux, feature
