Repository instrumentisto/medea-flutter-webrtc, pull requests merged in 2024-05, with the labels that each got.

#155 Upgrade libwebrtc 123.0.6312.105
  .clippy.toml
  CHANGELOG.md
  Cargo.lock
  README.md
  android/build.gradle
  android/src/main/kotlin/com/instrumentisto/medea_flutter_webrtc/model/RtpCapabilities.kt
  crates/libwebrtc-sys/Cargo.toml
  crates/libwebrtc-sys/build.rs
  crates/libwebrtc-sys/src/bridge.rs
  example/integration_test/webrtc_test.dart
  example/ios/Podfile.lock
  ios/Classes/controller/RtpTransceiverController.swift
  ios/Classes/model/Capabilities.swift
  ios/Classes/model/MediaType.swift
  ios/Classes/proxy/PeerConnectionFactoryProxy.swift
  ios/medea_flutter_webrtc.podspec
Labels: enhancement, k::dependencies

#156 Add audio gain control in `AudioConstraints`
  CHANGELOG.md
  lib/src/model/constraints.dart
Labels: enhancement, k::api, feature

#157 Implement `AudioConstraints.autoGainControl` for native platforms
  crates/libwebrtc-sys/include/adm.h
  crates/libwebrtc-sys/include/audio_device_recorder.h
  crates/libwebrtc-sys/include/bridge.h
  crates/libwebrtc-sys/include/local_audio_source.h
  crates/libwebrtc-sys/src/bridge.rs
  crates/libwebrtc-sys/src/cpp/adm.cc
  crates/libwebrtc-sys/src/cpp/audio_device_recorder.cc
  crates/libwebrtc-sys/src/cpp/bridge.cc
  crates/libwebrtc-sys/src/cpp/local_audio_source.cc
  crates/libwebrtc-sys/src/lib.rs
  crates/native/src/api.rs
  crates/native/src/bridge_generated.rs
  crates/native/src/devices.rs
  crates/native/src/lib.rs
  crates/native/src/user_media.rs
  lib/src/api/bridge.g.dart
  lib/src/api/bridge.g.freezed.dart
  lib/src/api/devices.dart
  lib/src/model/constraints.dart
Labels: enhancement, k::api, plarform::android, platform::macos, platform::linux, feature

#159 Fix `AudioSource` reuse after `PeerConnection` close
  crates/libwebrtc-sys/include/adm.h
  crates/libwebrtc-sys/include/bridge.h
  crates/libwebrtc-sys/src/bridge.rs
  crates/libwebrtc-sys/src/cpp/adm.cc
  crates/libwebrtc-sys/src/cpp/bridge.cc
Labels: enhancement, k::refactor, platform::windows, platform::macos, platform::linux

#160 Fix RTC stats on desktop platforms
  crates/libwebrtc-sys/src/cpp/stats.cc
  lib/src/model/stats.dart
Labels: enhancement, k::refactor, platform::windows, platform::macos, platform::linux
