Repository instrumentisto/medea-flutter-webrtc, pull requests merged in 2025-03, with the labels that each got.

#186 Upgrade libwebrtc 133.0.6943.98
  .github/workflows/ci.yml
  CHANGELOG.md
  Cargo.lock
  README.md
  android/build.gradle
  crates/libwebrtc-sys/Cargo.toml
  crates/libwebrtc-sys/build.rs
  crates/libwebrtc-sys/src/cpp/bridge.cc
  crates/native/build.rs
  example/ios/Podfile.lock
  ios/medea_flutter_webrtc.podspec
Labels: enhancement, k::toolchain, k::dependencies

#189 End local tracks when device is gone
  CHANGELOG.md
  Cargo.lock
  crates/native/src/api/mod.rs
  crates/native/src/devices.rs
  crates/native/src/frb_generated.rs
  crates/native/src/lib.rs
  crates/native/src/user_media.rs
  crates/native/src/video_sink.rs
  example/lib/src/get_user_media.dart
  lib/src/api/bridge/api.dart
  lib/src/api/bridge/frb_generated.dart
  lib/src/api/bridge/frb_generated.io.dart
  lib/src/platform/native/media_stream_track.dart
Labels: enhancement, k::api, k::design, platform::windows, platform::macos, platform::linux

#190 Upgrade libwebrtc 134.0.6998.35
  CHANGELOG.md
  Cargo.lock
  README.md
  android/build.gradle
  crates/libwebrtc-sys/Cargo.toml
  crates/libwebrtc-sys/build.rs
  example/ios/Podfile.lock
  ios/medea_flutter_webrtc.podspec
Labels: enhancement, k::toolchain, k::dependencies

#191 Build linux artifacts in debian:bookworm
  .github/workflows/ci.yml
Labels: enhancement, k::toolchain, platform::linux

#192 Get rid of useless frb threads
  CHANGELOG.md
  Cargo.lock
  android/build.gradle
  crates/native/Cargo.toml
  crates/native/src/api/mod.rs
  crates/native/src/devices.rs
  crates/native/src/frb.rs
  crates/native/src/frb_generated.rs
  crates/native/src/lib.rs
  crates/native/src/pc.rs
  example/ios/Podfile.lock
  example/macos/Podfile.lock
  example/pubspec.lock
  ios/medea_flutter_webrtc.podspec
  lib/src/api/bridge/api.dart
  lib/src/api/bridge/api.freezed.dart
  lib/src/api/bridge/frb_generated.dart
  lib/src/api/bridge/frb_generated.io.dart
  lib/src/api/bridge/lib.dart
  lib/src/api/bridge/renderer.dart
  macos/medea_flutter_webrtc.podspec
  pubspec.yaml
Labels: enhancement, k::refactor, platform::windows, platform::macos, platform::linux, k::dependencies, k::performance
