Repository instrumentisto/medea-flutter-webrtc, pull requests merged in 2025-06, with the labels that each got.

#203 Upgrade libwebrtc to 137.0.7151.55
  .github/workflows/ci.yml
  CHANGELOG.md
  Cargo.lock
  README.md
  android/build.gradle
  crates/libwebrtc-sys/Cargo.toml
  crates/libwebrtc-sys/build.rs
  crates/libwebrtc-sys/include/adm.h
  crates/libwebrtc-sys/include/adm_proxy.h
  crates/libwebrtc-sys/include/audio_device_recorder.h
  crates/libwebrtc-sys/include/bridge.h
  crates/libwebrtc-sys/include/delegating_apm.h
  crates/libwebrtc-sys/include/device_video_capturer.h
  crates/libwebrtc-sys/include/local_audio_source.h
  crates/libwebrtc-sys/include/mac_capturer.h
  crates/libwebrtc-sys/include/peer_connection.h
  crates/libwebrtc-sys/include/screen_video_capturer.h
  crates/libwebrtc-sys/include/stats.h
  crates/libwebrtc-sys/include/video_sink.h
  crates/libwebrtc-sys/src/bridge.rs
  crates/libwebrtc-sys/src/cpp/adm.cc
  crates/libwebrtc-sys/src/cpp/audio_device_recorder.cc
  crates/libwebrtc-sys/src/cpp/bridge.cc
  crates/libwebrtc-sys/src/cpp/delegating_apm.cc
  crates/libwebrtc-sys/src/cpp/device_video_capturer.cc
  crates/libwebrtc-sys/src/cpp/fake_frame_source.cc
  crates/libwebrtc-sys/src/cpp/local_audio_source.cc
  crates/libwebrtc-sys/src/cpp/mac_capturer.mm
  crates/libwebrtc-sys/src/cpp/peer_connection.cc
  crates/libwebrtc-sys/src/cpp/screen_video_capturer.cc
  crates/native/build.rs
  example/ios/Podfile.lock
  example/macos/Runner.xcodeproj/project.pbxproj
  ios/medea_flutter_webrtc.podspec
  macos/medea_flutter_webrtc.podspec
Labels: enhancement, k::refactor, k::toolchain, k::dependencies

#202 Release Android plugin resources when detached from Flutter engine
  CHANGELOG.md
  android/src/main/AndroidManifest.xml
  android/src/main/kotlin/com/instrumentisto/medea_flutter_webrtc/MedeaFlutterWebrtcPlugin.kt
  android/src/main/kotlin/com/instrumentisto/medea_flutter_webrtc/MediaDevices.kt
  android/src/main/kotlin/com/instrumentisto/medea_flutter_webrtc/State.kt
  android/src/main/kotlin/com/instrumentisto/medea_flutter_webrtc/controller/Controller.kt
  android/src/main/kotlin/com/instrumentisto/medea_flutter_webrtc/controller/ControllerRegistry.kt
  android/src/main/kotlin/com/instrumentisto/medea_flutter_webrtc/controller/IdentifiableController.kt
  android/src/main/kotlin/com/instrumentisto/medea_flutter_webrtc/controller/MediaDevicesController.kt
  android/src/main/kotlin/com/instrumentisto/medea_flutter_webrtc/controller/MediaStreamTrackController.kt
  android/src/main/kotlin/com/instrumentisto/medea_flutter_webrtc/controller/PeerConnectionController.kt
  android/src/main/kotlin/com/instrumentisto/medea_flutter_webrtc/controller/PeerConnectionFactoryController.kt
  android/src/main/kotlin/com/instrumentisto/medea_flutter_webrtc/controller/RtpSenderController.kt
  android/src/main/kotlin/com/instrumentisto/medea_flutter_webrtc/controller/RtpTransceiverController.kt
  android/src/main/kotlin/com/instrumentisto/medea_flutter_webrtc/controller/VideoRendererController.kt
  android/src/main/kotlin/com/instrumentisto/medea_flutter_webrtc/controller/VideoRendererFactoryController.kt
  android/src/main/kotlin/com/instrumentisto/medea_flutter_webrtc/proxy/AudioMediaTrackSource.kt
  android/src/main/kotlin/com/instrumentisto/medea_flutter_webrtc/proxy/MediaStreamTrackProxy.kt
  android/src/main/kotlin/com/instrumentisto/medea_flutter_webrtc/proxy/PeerConnectionFactoryProxy.kt
  android/src/main/kotlin/com/instrumentisto/medea_flutter_webrtc/proxy/PeerConnectionProxy.kt
  android/src/main/kotlin/com/instrumentisto/medea_flutter_webrtc/proxy/PeerObserver.kt
  android/src/main/kotlin/com/instrumentisto/medea_flutter_webrtc/proxy/Proxy.kt
  android/src/main/kotlin/com/instrumentisto/medea_flutter_webrtc/proxy/RtpTransceiverProxy.kt
  android/src/main/kotlin/com/instrumentisto/medea_flutter_webrtc/proxy/VideoMediaTrackSource.kt
  example/android/app/build.gradle.kts
  example/android/app/src/main/AndroidManifest.xml
  lib/src/platform/native/media_stream_track.dart
Labels: enhancement, k::refactor, plarform::android

#208 Refactor pub fields in tracks
  crates/native/src/devices.rs
  crates/native/src/pc.rs
  crates/native/src/user_media.rs
Labels: enhancement, k::refactor
