Repository instrumentisto/medea-flutter-webrtc, pull requests merged in 2025-07, with the labels that each got.

#233 Upgrade libwebrtc to 138.0.7204.49
  CHANGELOG.md
  Cargo.lock
  README.md
  android/build.gradle
  crates/libwebrtc-sys/Cargo.toml
  crates/libwebrtc-sys/build.rs
  crates/libwebrtc-sys/src/cpp/screen_video_capturer.cc
  example/ios/Podfile.lock
  example/macos/Podfile.lock
  ios/medea_flutter_webrtc.podspec
Labels: enhancement, k::dependencies

#217 Move RtcStats into separate module
  crates/native/src/api/mod.rs
  crates/native/src/api/stats/ice_role.rs
  crates/native/src/api/stats/mod.rs
  crates/native/src/api/stats/rtc_ice_candidate_stats.rs
  crates/native/src/api/stats/rtc_inbound_rtp_stream_media_type.rs
  crates/native/src/api/stats/rtc_media_source_stats_media_type.rs
  crates/native/src/api/stats/rtc_outbound_rtp_stream_media_type.rs
  crates/native/src/api/stats/rtc_stats_ice_candidate_pair_state.rs
  crates/native/src/frb_generated.rs
  crates/native/src/lib.rs
  lib/src/api/bridge/api.dart
  lib/src/api/bridge/api.freezed.dart
  lib/src/api/bridge/api/stats.dart
  lib/src/api/bridge/api/stats.freezed.dart
  lib/src/api/bridge/api/stats/ice_role.dart
  lib/src/api/bridge/api/stats/rtc_ice_candidate_stats.dart
  lib/src/api/bridge/api/stats/rtc_ice_candidate_stats.freezed.dart
  lib/src/api/bridge/api/stats/rtc_inbound_rtp_stream_media_type.dart
  lib/src/api/bridge/api/stats/rtc_inbound_rtp_stream_media_type.freezed.dart
  lib/src/api/bridge/api/stats/rtc_media_source_stats_media_type.dart
  lib/src/api/bridge/api/stats/rtc_media_source_stats_media_type.freezed.dart
  lib/src/api/bridge/api/stats/rtc_outbound_rtp_stream_media_type.dart
  lib/src/api/bridge/api/stats/rtc_outbound_rtp_stream_media_type.freezed.dart
  lib/src/api/bridge/api/stats/rtc_stats_ice_candidate_pair_state.dart
  lib/src/api/bridge/frb_generated.dart
  lib/src/api/bridge/frb_generated.io.dart
  lib/src/api/peer.dart
  lib/src/model/stats.dart
Labels: enhancement, k::refactor, k::api

#209 Refactor `AudioTrack` and `VideoTrack` into generic `Track`
  crates/native/src/api/mod.rs
  crates/native/src/devices.rs
  crates/native/src/lib.rs
  crates/native/src/media/device.rs
  crates/native/src/media/mod.rs
  crates/native/src/media/source.rs
  crates/native/src/media/track.rs
  crates/native/src/pc.rs
  crates/native/src/user_media.rs
  crates/native/src/video_sink.rs
Labels: enhancement, k::refactor

#214 Move `RtpCapabilities` into separate module
  crates/native/src/api/capability/mod.rs
  crates/native/src/api/capability/rtp_codec/mod.rs
  crates/native/src/api/capability/rtp_codec/rtcp_feedback.rs
  crates/native/src/api/capability/rtp_codec/scalability_mode.rs
  crates/native/src/api/capability/rtp_header_extension_capability.rs
  crates/native/src/api/mod.rs
  crates/native/src/frb_generated.rs
  lib/src/api/bridge/api.dart
  lib/src/api/bridge/api/capability.dart
  lib/src/api/bridge/api/capability/rtp_codec.dart
  lib/src/api/bridge/api/capability/rtp_codec/rtcp_feedback.dart
  lib/src/api/bridge/api/capability/rtp_codec/scalability_mode.dart
  lib/src/api/bridge/api/capability/rtp_header_extension_capability.dart
  lib/src/api/bridge/frb_generated.dart
  lib/src/api/bridge/frb_generated.io.dart
  lib/src/api/receiver.dart
  lib/src/api/sender.dart
  lib/src/api/transceiver.dart
  lib/src/model/capability.dart
Labels: enhancement, k::refactor

#222 Move `MediaStreamTrack` into separate module
  crates/native/src/api/media_stream_track/audio_processing_config.rs
  crates/native/src/api/media_stream_track/media_type.rs
  crates/native/src/api/media_stream_track/mod.rs
  crates/native/src/api/media_stream_track/track_event.rs
  crates/native/src/api/media_stream_track/track_state.rs
  crates/native/src/api/mod.rs
  crates/native/src/frb_generated.rs
  lib/src/api/bridge/api.dart
  lib/src/api/bridge/api.freezed.dart
  lib/src/api/bridge/api/capability.dart
  lib/src/api/bridge/api/capability/rtp_codec.dart
  lib/src/api/bridge/api/media_stream_track.dart
  lib/src/api/bridge/api/media_stream_track.freezed.dart
  lib/src/api/bridge/api/media_stream_track/audio_processing_config.dart
  lib/src/api/bridge/api/media_stream_track/media_type.dart
  lib/src/api/bridge/api/media_stream_track/track_event.dart
  lib/src/api/bridge/api/media_stream_track/track_event.freezed.dart
  lib/src/api/bridge/api/media_stream_track/track_state.dart
  lib/src/api/bridge/frb_generated.dart
  lib/src/api/bridge/frb_generated.io.dart
  lib/src/api/devices.dart
  lib/src/api/peer.dart
  lib/src/api/receiver.dart
  lib/src/api/sender.dart
  lib/src/api/transceiver.dart
  lib/src/platform/native/media_stream_track.dart
  lib/src/platform/native/video_renderer.dart
Labels: enhancement, k::refactor, k::api

#223 Move RtcRtpEncodingParameters into separate module
  crates/native/src/api/mod.rs
  crates/native/src/api/rtc_rtp_encoding_parameters.rs
  crates/native/src/frb_generated.rs
  lib/src/api/bridge/api.dart
  lib/src/api/bridge/api/rtc_rtp_encoding_parameters.dart
  lib/src/api/bridge/frb_generated.dart
  lib/src/api/bridge/frb_generated.io.dart
  lib/src/api/send_encoding_parameters.dart
Labels: enhancement, k::refactor, k::api

#231 Move peer API logic into separate module
  crates/native/src/api/mod.rs
  crates/native/src/api/peer/events/ice_connection_state.rs
  crates/native/src/api/peer/events/ice_gathering_state.rs
  crates/native/src/api/peer/events/mod.rs
  crates/native/src/api/peer/events/peer_connection_state.rs
  crates/native/src/api/peer/events/rtc_track_event.rs
  crates/native/src/api/peer/events/signaling_state.rs
  crates/native/src/api/peer/mod.rs
  crates/native/src/api/peer/rtc_configuration/bundle_policy.rs
  crates/native/src/api/peer/rtc_configuration/ice_transports_type.rs
  crates/native/src/api/peer/rtc_configuration/mod.rs
  crates/native/src/api/peer/rtc_configuration/rtc_ice_server.rs
  crates/native/src/api/peer/rtc_session_description.rs
  crates/native/src/api/peer/video_codec_info.rs
  crates/native/src/frb_generated.rs
  lib/src/api/bridge/api.dart
  lib/src/api/bridge/api/peer.dart
  lib/src/api/bridge/api/peer/events.dart
  lib/src/api/bridge/api/peer/events.freezed.dart
  lib/src/api/bridge/api/peer/events/ice_connection_state.dart
  lib/src/api/bridge/api/peer/events/ice_gathering_state.dart
  lib/src/api/bridge/api/peer/events/peer_connection_state.dart
  lib/src/api/bridge/api/peer/events/rtc_track_event.dart
  lib/src/api/bridge/api/peer/events/signaling_state.dart
  lib/src/api/bridge/api/peer/rtc_configuration.dart
  lib/src/api/bridge/api/peer/rtc_configuration/bundle_policy.dart
  lib/src/api/bridge/api/peer/rtc_configuration/ice_transports_type.dart
  lib/src/api/bridge/api/peer/rtc_configuration/rtc_ice_server.dart
  lib/src/api/bridge/api/peer/rtc_rtp_transceiver.dart
  lib/src/api/bridge/api/peer/rtc_session_description.dart
  lib/src/api/bridge/api/peer/video_codec_info.dart
  lib/src/api/bridge/frb_generated.dart
  lib/src/api/bridge/frb_generated.io.dart
  lib/src/api/peer.dart
  lib/src/model/peer.dart
Labels: enhancement, k::refactor

#232 Move media devices API into separate module
  crates/native/src/api/media/constraints/audio.rs
  crates/native/src/api/media/constraints/mod.rs
  crates/native/src/api/media/constraints/video.rs
  crates/native/src/api/media/mod.rs
  crates/native/src/api/mod.rs
  crates/native/src/frb_generated.rs
  lib/src/api/bridge/api.dart
  lib/src/api/bridge/api/media.dart
  lib/src/api/bridge/api/media/constraints.dart
  lib/src/api/bridge/api/media/constraints/audio.dart
  lib/src/api/bridge/api/media/constraints/video.dart
  lib/src/api/bridge/api/media_stream_track.dart
  lib/src/api/bridge/frb_generated.dart
  lib/src/api/bridge/frb_generated.io.dart
  lib/src/api/devices.dart
  lib/src/platform/native/media_stream_track.dart
Labels: enhancement, k::refactor, k::api

#240 Add `codegen` check to CI
  .github/workflows/ci.yml
  CHANGELOG.md
  Makefile
Labels: k::toolchain, feature
